version: "{branch}.build.{build}"
skip_tags: true

branches:
  only:
    - develop

clone_folder: c:\projects\php_printer

install:
  ps: |

    echo "Build cache directory c:\build-cache"
    if (-not (Test-Path c:\build-cache)) {
        mkdir c:\build-cache
    }

    echo "Download PHP SDK binary tools"
    $bname = 'php-sdk-binary-tools-php-sdk-' + $env:BIN_SDK_VER + '.zip'
    $bpath = 'php-sdk-' + $env:BIN_SDK_VER
    echo "Downloading: https://github.com/php/php-sdk-binary-tools/releases/download/$bpath/$bname"
    if (-not (Test-Path c:\build-cache\$bname)) {
        Invoke-WebRequest "https://github.com/php/php-sdk-binary-tools/releases/download/$bpath/$bname" -OutFile "c:\build-cache\$bname"
    }
    $dname0 = 'php-sdk-binary-tools-php-sdk-' + $env:BIN_SDK_VER
    $dname1 = 'php-sdk-' + $env:BIN_SDK_VER
    if (-not (Test-Path c:\build-cache\$dname1)) {
        7z x c:\build-cache\$bname -oc:\build-cache
        Start-Sleep -s 5
        move c:\build-cache\$dname0 c:\build-cache\$dname1
    }

    # Download full PHP source
    echo "Downloading full PHP source for $($env:PHP_VER)"
    $src_zip = "php-src-php-$($env:PHP_VER).zip"
    $src_url = "https://github.com/php/php-src/archive/refs/tags/php-$($env:PHP_VER).zip"
    if (-not (Test-Path c:\build-cache\$src_zip)) {
        Invoke-WebRequest $src_url -OutFile "c:\build-cache\$src_zip"
    }
    if (-not (Test-Path c:\projects\php-src)) {
        7z x c:\build-cache\$src_zip -oC:\projects\
        move C:\projects\php-src-php-* C:\projects\php-src
    }

    # Copy your extension into the source tree
    echo "Copy extension to php-src\ext\printer"
    xcopy c:\projects\php_printer C:\projects\php-src\ext\printer\ /s /e /y /f /i

cache:
  c:\build-cache -> .appveyor.yml
  c:\projects\php-src -> .appveyor.yml

environment:
  BIN_SDK_VER: 2.3.0
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      ARCH: x64
      VC: vs17
      PHP_VER: 8.4.17
      TS: 1

build_script:
  ps: |
    $runner = 'c:\build-cache\php-sdk-' + $env:BIN_SDK_VER + '\phpsdk' + '-' + $env:VC + '-' + $env:ARCH + '.bat'
    $ts_part = if ($env:TS -eq '1') { 'ts' } else { '-nts' }

    # Prepare deps in full source tree
    echo "Preparing dependencies"
    cd C:\projects\php-src
    echo "" | Out-File -Encoding "ASCII" deps_task.bat
    echo "bin\phpsdk_deps --update --force --branch 8.4 --arch x64 -d deps" | Out-File -Encoding "ASCII" -Append deps_task.bat
    & $runner -t deps_task.bat

    # Buildconf
    echo "Running buildconf"
    .\buildconf.bat --force

    # Configure
    echo "Configuring PHP"
    $ts_flag = if ($env:TS -eq '1') { '--enable-zts' } else { '--disable-zts' }
    $conf_cmd = "configure $ts_flag --enable-debug --enable-gd=shared --enable-printer=shared --with-php-build=deps"
    echo "" | Out-File -Encoding "ASCII" task.bat
    echo $conf_cmd | Out-File -Encoding "ASCII" -Append task.bat
    echo "nmake /nologo" | Out-File -Encoding "ASCII" -Append task.bat
    echo "exit %errorlevel%" | Out-File -Encoding "ASCII" -Append task.bat
    & $runner -t task.bat

after_build:
  ps: |

    echo "Build download archive of build extension and save as artifact..."
    $ts_part = 'ts'
    if ('0' -eq $env:TS) { $ts_part = '-nts' }
    $zip_bname = 'php_printer-' + $env:APPVEYOR_REPO_COMMIT.substring(0, 8) + '-' + $env:PHP_VER.substring(0, 3) + '-' + $ts_part + '-' + $env:VC + '-' + $env:ARCH + '.zip'
    $dir = 'c:\projects\php-src\';
    if ('x64' -eq $env:ARCH) { $dir = $dir + 'x64\' }
    $dir = $dir + 'Release'
    if ('1' -eq $env:TS) { $dir = $dir + '_TS' }
    & 7z a c:\$zip_bname $dir\php_printer.dll
    Push-AppveyorArtifact c:\$zip_bname

test_script:
  ps: |

    echo "Start tests..."